### ISSUE TITLE
Issue with Poker Hands Statistics

### ISSUE THREAD

**Issue by complex11011** [GauntletGames-2086/Flower-Pot#1]
"High Card" poker hand is displayed as "ERROR" in the UI.

![image](https://github.com/user-attachments/assets/267e1229-bc07-48fc-ada7-55f3877e4cea)

**Comment by complex11011** [comment]
Noted that this is also possible with other hands. I'm not sure what is causing it.

![image](https://github.com/user-attachments/assets/04968401-ec7f-4315-8223-6a6fef71ce6c)

Modlist:
- Achievement enabler
- Aurinko
- Bunco
- Cardsleeves
- Cryptid
- DebugPlus
- Familiar
- Fusion Jokers
- Galdur
- Incantation
- Jen's Almanac
- JenLib
- KCVanilla
- Loop
- MoreFluff
- Betmma's Mods
- Nopeus
- SDM_0's stuff
- Steamodded
- Talisman
- Flower Pot

**Comment by complex11011** [comment]
The issue resolves itself upon resetting the profile, so the issue could be related to the profile somehow?

**Comment by GauntletGames-2086** [comment]
It's likely to do with profile stat saving a poker hand key that's not the same as the key used for localization. Possible fix has just been pushed.

**Comment by complex11011** [comment]
Issue is fixed in latest version
